name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: false
        default: 'QA'
        type: choice
        options:
          - QA
          - DEV

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Update Helm Values
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: twelvelabs-io/tl-test-automation
          event-type: e2e_tests_trigger
          client-payload: |
            {
              "environment": "DEV",
              "base_url": "https://playground-dev-git-fro-1750-redirect-to-feat-ca1532-twelve-labs.vercel.app",
              "source_repo": "twelvelabs-io/tl-youtube-timeline",
              "pr_number": "1693",
              "workflow_run_id": "${{ github.run_id }}",
              "triggered_by": "vercel_deployment"
            }